Update install-with-secrets
Signed-off-by: lessuseless <179788364+lessuselesss@users.noreply.github.com>

diff --git a/apps/x86_64-linux/install-with-secrets b/apps/x86_64-linux/install-with-secrets
--- a/apps/x86_64-linux/install-with-secrets
+++ b/apps/x86_64-linux/install-with-secrets
@@ -1,6 +1,18 @@
 #!/usr/bin/env bash
 set -exu
 
+# Detect current branch, default to 'main' if not in a git repo
+if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
+  BRANCH=$(git rev-parse --abbrev-ref HEAD)
+else
+  BRANCH="main"
+fi
+export BRANCH
+
+cleanup() {
+  rm -rf "dustinlyons-nixos-config-${BRANCH}.zip" "dustinlyons-nixos-config-${BRANCH}" nixos-config
+}
+
 check_installer() {
   if [ -e /etc/NIXOS ]; then
     echo -e "\e[1;32mRunning in the NixOS installer environment.\e[0m"
@@ -10,14 +22,10 @@ check_installer() {
   fi
 }
 
-cleanup() {
-  rm -rf dustinlyons-nixos-config-main.zip dustinlyons-nixos-config-main nixos-config
-}
-
 download_config() {
-  curl -LJ0 https://github.com/lessuselesss/dustinlyons-nixos-config/archive/main.zip -o dustinlyons-nixos-config-main.zip
-  unzip dustinlyons-nixos-config-main.zip
-  mv dustinlyons-nixos-config-main/templates/starter-with-secrets nixos-config
+  curl -LJ0 "https://github.com/lessuselesss/dustinlyons-nixos-config/archive/${BRANCH}.zip" -o "dustinlyons-nixos-config-${BRANCH}.zip"
+  unzip "dustinlyons-nixos-config-${BRANCH}.zip"
+  mv "dustinlyons-nixos-config-${BRANCH}/templates/starter" nixos-config
   cd nixos-config
 }
 
@@ -46,6 +54,10 @@ setup_files() {
 }
 
 setup_ssh_keys() {
+  if [ -z "${USERNAME:-}" ]; then
+    echo "USERNAME is not set. Aborting."
+    exit 1
+  fi
   mkdir -p /mnt/home/${USERNAME}/.ssh
   chown nixos /mnt/home/${USERNAME}/.ssh
 
@@ -60,7 +72,15 @@ setup_ssh_keys() {
 }
 
 link_home_dir() {
-  ln -s /mnt/home/${USERNAME} /home/${USERNAME} # Used to grab initial secrets
+  if [ -z "${USERNAME:-}" ]; then
+    echo "USERNAME is not set. Aborting."
+    exit 1
+  fi
+  if [ ! -e "/home/${USERNAME}" ]; then
+    ln -s /mnt/home/${USERNAME} /home/${USERNAME} # Used to grab initial secrets
+  else
+    echo "/home/${USERNAME} already exists, skipping symlink."
+  fi
 }
 
 install_nixos() {
